### ISSUE TITLE
Add documentation pages

### ISSUE THREAD

**Issue by PGijsbers** [aiondemand/aiondemand#6]
We need (static) documentation pages which document basic usage and serve as an API reference.
There has been some work on sphinx docs, but using `mkdocs` (with the `material` theme) will make it much easier to provide a more modern experience.

- [ ] Update the documentation framework
- [ ] Generate the API reference
- [ ] Incorporate example code

**Comment by PGijsbers** [comment]
Unfortunately, `mkdocstrings` does not (yet) work for generating API documentation for our dynamically generated methods. The author is working on making it work better with introspection, but it might be a while. Sphinx does seem to work though (but we do need to explicitly make the submodules discoverable with `__all__`). So this gives three choices:

 - Use Sphinx after all (at least for the API reference).
 - Wait for `mkdocstrings`/`griffe` to be updated to generate the API reference section.
 - Write a small script which makes a code dump through own introspection, then generate the API page from that code with `mkdocstrings`. This will not be able to link directly to the source code, however.

**Comment by PGijsbers** [comment]
I am leaning towards doing a small test with option 3, as the desired end goal would be option 2 but we need the result faster. Doing this would make the documentation feel more consistent than option 1, and users will have (almost) no difference once we can actually simply use the fixed tools.

**Comment by pawamoy** [comment]
I'm making good progress, I believe it's a matter of days before Griffe is able to use introspection on a full package :)

**Comment by pawamoy** [comment]
By the way, it's possible to selectively load objects with introspection while the rest is done through static analysis. I'll show you an example tomorrow.

**Comment by pawamoy** [comment]
Here you go:

```python
# griffe_extensions.py
from ast import AST
from griffe.agents.nodes import ObjectNode
from griffe.dataclasses import Module
from griffe.extensions import Extension
from griffe.agents.inspector import inspect


class DynamicAnalysisExtension(Extension):
    # Define our init method and the options that can be passed from `mkdocs.yml`.
    def __init__(self, modules: list[str]) -> None:
        self.modules = modules

    # Once the static analyzer has finished scanning a module,
    # we do a second pass using dynamic analysis.
    # We don't do it before because the static analysis would overwrite our changes.
    def on_module_members(self, *, node: AST | ObjectNode, mod: Module) -> None:
        # Object nodes mean we're already doing dynamic analysis.
        if isinstance(node, ObjectNode):
            return

        # Skip unselected modules.
        if mod.path not in self.modules:
            return

        # Inspect the module using dynamic analysis.
        inspected_module = inspect(mod.path, filepath=mod.filepath)

        # Discard all previous existing members obtained through static analysis,
        # and replace them with those obtained through dynamic analysis.
        for name, member in inspected_module.members.items():
            if member in mod.members:
                mod.del_member(name)
            mod.set_member(name, member)
```

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_extensions.py:
              modules:
              - path.to.your.modules
```

With a tiny bit more work, you can probably pass explicit lists of members to keep for each module :slightly_smiling_face:

**Comment by pawamoy** [comment]
See https://mkdocstrings.github.io/griffe/extensions/ to learn more about how to write/use extensions :slightly_smiling_face:

**Comment by PGijsbers** [comment]
Sorry for the slow reply, I had a busy two weeks. I added the Python file to the root of our project and updated `mkdocs.yml` to include the extension. But I don't think it is used (e.g., setting a `breakpoint()` in the file does not pause execution, and the generated docs are identical). I am also not getting the expected outcome with 
```
(venv) ➜  aiod-py-sdk git:(docs) ✗ griffe dump aiod --extension '[
 {"griffe_extensions.py:DynamicAnalysisExtension":{"modules":["aiod","aiod.case_studies"]}}]'
```
It is the same as `griffe dump aiod`.

I am sure I am doing something wrong, but I have a hard time figuring out what. I would very much appreciate some help.

Using `griffe 0.44.0` and `mkdocstrings 0.25.1` and `mkdocstrings-python 1.10.2`.

**Comment by pawamoy** [comment]
Do you have a branch I should checkout to verify?

**Comment by PGijsbers** [comment]
Hm. I cannot reproduce it anymore, it seems to kind-of-work now. But the output is still different from what I would expect in two ways. 

### Failure to resolve dependencies

First, I have to import the module (`aiod`) in `griffe_extensions.py`, otherwise the dynamic import fails to resolve dependencies:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 366, in <module>
    cli()
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 268, in serve_command
    serve.serve(**kwargs)
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 85, in serve
    builder(config)
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 310, in build
    _populate_page(file.page, config, files, dirty)
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 167, in _populate_page
    page.render(config, files)
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocs/structure/pages.py", line 285, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/markdown/core.py", line 357, in convert
    root = self.parser.parseDocument(self.lines).getroot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/markdown/blockparser.py", line 117, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/markdown/blockparser.py", line 136, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/markdown/blockparser.py", line 158, in parseBlocks
    if processor.run(parent, blocks) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocstrings/extension.py", line 128, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocstrings/extension.py", line 210, in _process_block
    data: CollectorItem = handler.collect(identifier, options)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line 315, in collect
    loader.load(
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/griffe/loader.py", line 226, in load
    top_module = self._load_package(package, submodules=submodules)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/griffe/loader.py", line 524, in _load_package
    top_module = self._load_module(package.name, package.path, submodules=submodules)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pietergijsbers/repositories/tmp/aiondemand/venv/lib/python3.11/site-packages/griffe/loader.py", line 552, in _load_module
    raise LoadingError(f"Import error: {error}") from error
griffe.exceptions.LoadingError: Import error: With sys.path = ['/Users/pietergijsbers/repositories/tmp/aiondemand/src'], accessing 'aiod' raises ModuleNotFoundError: No module named 'requests'
```

After adding a `import aiod` statement to the `griffe_extension.py`, the docs build successfully (but with incorrect text, see below).

### Documentation is different from docstrings

Second, the original method is being added to the documentation instead of the wrapped-and-patched one. 
One example of the render (from the `aiod.case_studies` section):
![image](https://github.com/aiondemand/aiondemand/assets/15890747/2a7515a2-70eb-4826-b4b6-724d8ffd9a2e)

If we use introspection to look at the function `__doc__`, we get a different text:

```
>>> aiod.case_studies.get_list.__doc__
'\n    Retrieve a list of case_studies from the catalogue.\n\n    Parameters (keywords required):\n        platform (str | None): Return metadata of case_studies assets of this platform (default is None).\n        offset (int): The offset for pagination (default is 0).\n        limit (int): The maximum number of items to retrieve (default is 10).\n        version (str | None): The version of the endpoint (default is None).\n        data_format (Literal["pandas", "json"]): The desired format for the response (default is "pandas").\n            For "json" formats, the returned type is a json decoded type, i.e. in this case a list of dict\'s.\n\n    Returns:\n        pd.DataFrame | list[dict]: The retrieved metadata in the specified format.\n    '
```

Note that `ASSET_TYPE` has been substituted for `case_studies`, as expected.


### Reproducible example

You should be able to reproduce the behavior from the `mkdocstrings` branch:

```
git clone https://github.com/aiondemand/aiondemand.git
git checkout mkdocstrings

python -m venv venv
source venv/bin/activate

python -m pip install -e .
python -m pip install -r requirements.txt # excuse the mess
```
after adding the `import aiod` statement to `griffe_extension.py` you should also be able to serve the docs successfully.

Verify with checking the rendered documentation to and comparing it to
```python
import aiod
aiod.case_studies.get_list.__doc__
```

**Comment by pawamoy** [comment]
Thanks, this helped.

First, an update to the `inspect` call so that you don't have to add `import aiod`:

```python
        # Inspect the module using dynamic analysis.
        inspected_module = inspect(
            mod.name,
            filepath=mod.filepath,
            parent=mod.parent,
            import_paths=list(sys.path),
        )
```

Second, the issue is that the `get_list` object that you get back in the `case_studies` module still declares its parent module to be `aiod.calls.calls`. So Griffe considers it an alias (imported from elsewhere). When resolving that alias, it uses `aio.calls.calls.get_list`, so you get the original, unchanged function.

There's no way for Griffe to correctly understand that `get_list` (and siblings) are not aliases but actual objects to be inspected directly[^1], unless you help it understand. To help it understand that, you would have to also patch the functions' `__module__` attribute to point to the module they are assigned into (`aiod.resources.case_studies`), so that Griffe understands they're actual child of this module, and not aliases.

[^1]: Griffe *has* to separate objects declared within a module from objects imported from other modules to avoid weird recursive cases, and also for performance reasons (we don't want to inspect again and again modules and classes and all their children every time they appear somewhere).

**Comment by pawamoy** [comment]
Hmmm actually there's another issue. Griffe unwraps objects when inspecting them, so it'll always look at `aiod.calls.calls.get_list` anyway :thinking: Unwrapping is done for the same reasons as above: getting the underlying, declared object instead of the wrapper (think decorators, etc.).

I'll have to think about this a bit more.

**Comment by pawamoy** [comment]
Maybe, if you don't actually need to reference to the wrapped function, you could hide it away, so that Griffe uses the wrapper (with updated `__doc__`), instead of the wrapped function :thinking:

**Comment by pawamoy** [comment]
So, possible workaround:

```python
(
    get_list,
    counts,
    get_asset,
    get_asset_from_platform,
    get_content,
    get_assets_async,
    get_list_async,
) = calls.wrap_common_calls(asset_type="case_studies", module=__name__)
```

```python
def wrap_calls(asset_type: str, calls: list[Callable], module: str) -> Tuple[Callable, ...]:
    wrapper_list = []
    for wrapped in calls:
        wrapper: Callable = partial(wrapped, asset_type=asset_type)
        # wrapper = update_wrapper(wrapper, wrapped)
        wrapper.__doc__ = (
            wrapped.__doc__.replace("ASSET_TYPE", asset_type)
            if wrapped.__doc__ is not None
            else ""
        )
        wrapper.__module__ = module
        wrapper_list.append(wrapper)

    return tuple(wrapper_list)
```

Something like that. I'm gonna try that.

**Comment by pawamoy** [comment]
> TypeError: '<' not supported between instances of 'NoneType' and 'int'

Oh yes, I encountered this as well, I have opened this issue: https://github.com/mkdocstrings/python/issues/163. Let me fix it.

**Comment by PGijsbers** [comment]
Thanks! I disabled `show_source` for now :)

**Comment by PGijsbers** [comment]
Still experiencing two issues. They are reproducible from the `docs/mkdocstrings` branch on this repo.

1. **The function signature is only rendered correctly for `async` methods.** The following examples are rendered from the exact same code, only changing the addition/removal of the `async` keyword in the function definition inbetween.
With `async` in the definition: 
![image](https://github.com/aiondemand/aiondemand/assets/15890747/81276054-cc44-4c41-b28d-b4febaa80834)
Without `async` in the definition:
![image](https://github.com/aiondemand/aiondemand/assets/15890747/0283ec42-a3ea-46d5-b5d7-ee2e19f3630e)

2. **The docstrings do not render correctly. This seems to be an artifact from the way the objects are discovered (with `griffe_extensions.py`).** The following MWE renders as expected (with `mkdocs-material` and `mkdocstrings-python` installed):

`mkdocs.yml`:
```yaml
site_name: test
theme:
  name: material

plugins:
  - mkdocstrings
```

`package/__init__.py`:
```python
def my_function(a: int, b: str | None = None) -> int:
  """This is an example.

  Args:
    a: first parameter.
    b: second parameter. defaults to none.

  Returns:
    Some number

  """
  print(a, b)
  return 42
```

`docs/readme.md`:
```markdown
::: package
```
Results in t he render:
![image](https://github.com/aiondemand/aiondemand/assets/15890747/b7315bb4-61bb-45bb-aa7c-b7a58fb721ec)

However, when I add the exact same `my_function` function to `src/aiod/__init__.py` (or alternatively, registering the `griffe_extensions.py` in the MWE), it renders instead as:

![image](https://github.com/aiondemand/aiondemand/assets/15890747/f5537781-896d-44da-82f4-bb8acca64e6f)

@pawamoy do you have any idea what is happening here?

**Comment by pawamoy** [comment]
Ah, it looks like the docstring is not parsed: you might need to pass `docstring_parser="google"` to `inspect`.

**Comment by PGijsbers** [comment]
Re-enabling the `update_wrapper` in the function that we used to created the partials seems to work, i.e. this line from our code:

```diff
- # wrapper = update_wrapper(wrapper, wrapped)
+ wrapper = update_wrapper(wrapper, wrapped)
```

Will get the function signatures to show up correctly[^1]. I stumbled upon this because I noticed that the type hints for the wrapped functions were not picked up by (which reminded me that we no longer copied over all function metadata). I tried re-enabling it, and it seemed to work without issue this time.

Just to help my understanding, does `mkdocstrings` translate the data to markdown, and have mkdocs take care of converting it to doc pages? Simply inserting it with some mkdocs `on_page_markdown` hook or something?

[^1]: Though it still shows up with the `asset_type` parameter, which seems correct as it is still a parameter even if it now has a default, but something we would prefer not to communicate in the API docs. I guess that's for us to figure out :)

**Comment by PGijsbers** [comment]
Nevermind, I had missed that the `ASSET_TYPE` was not substituted correctly. So we are back to the situation:

 - with `update_wrapper`: it is correctly identified as a function - in fact it simply displays the original function docs (so no updated docstring, no default for `asset_type`.
 - without `update_wrapper`: it renders the correct docs, but the signature is not displayed and the type annotations are ignored. 
 
 The latter seems to be an issue because for whatever reason the function is then treated again as an attribute instead of a function. Trying to dig to the part of the code which determines that.

**Comment by PGijsbers** [comment]
If `griffe/agents/nodes/_runtime.py#L126` would recognize the partial as a function and not an attribute, then it looks like everything works as expected.

**Comment by pawamoy** [comment]
Hey again @PGijsbers, thanks for your patience :slightly_smiling_face: I've followed your suggestion to detect partials as functions, and to me that finally fixes the issue :slightly_smiling_face: 

![getasset](https://github.com/aiondemand/aiondemand/assets/3999221/9f39c692-6c2c-4938-9d70-d325d36c1664)

The last minor issue is that your wrapper writes `Parameters (keywords required):` for the parameters section, preventing the parser from parsing it as a parameters section. For it to be parsed correctly you have to remove `(keywords required)`.

Let me know if it works for you! Also, thank you so much for your one-time sponsorship, greatly appreciate it! :heart:

**Comment by PGijsbers** [comment]
> I'll push a bugfix release in the coming hour.

Wow, that's great! :)

> One minor issue is that your docstrings writes [...]

Yea, we caught that one already. Thanks for pointing it out though! :)

> Another possible issue is that the signature of the partial still shows the asset_type parameter, [...]

Yes, that's correct. I do think this should be the correct behavior for mkdocstrings[^1], even if we don't want it in our documentation. We wrote a mkdocs plugin instead to remove that from the documentation on our end, so it better reflects the intended use of the function.

> Also, thank you so much for your one-time sponsorship, greatly appreciate it! ❤️

And thank you for all the help! ❤️ 

[^1]: Partials behave as though they overwrite defaults only, as opposed to acting like they provide an additional keyword argument in which case you would expect a `SyntaxError: keyword argument repeated`.
